// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTrI7dr8Of3huZqE2D7lehir8tzbnVle4',
    appId: '1:75929189588:web:e38e0efce95a98e287cf41',
    messagingSenderId: '75929189588',
    projectId: 'cinco-tigres-felizes',
    authDomain: 'cinco-tigres-felizes.firebaseapp.com',
    storageBucket: 'cinco-tigres-felizes.firebasestorage.app',
    measurementId: 'G-J8KFNNV82W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsQSgseEDZLGHXnZ6_wqwoNOsWCgeqZFI',
    appId: '1:75929189588:android:aabd24f24915355887cf41',
    messagingSenderId: '75929189588',
    projectId: 'cinco-tigres-felizes',
    storageBucket: 'cinco-tigres-felizes.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU5tJPMl6meJ9afw6x76pgGyH9vCK9Rgo',
    appId: '1:75929189588:ios:f36017b70238adab87cf41',
    messagingSenderId: '75929189588',
    projectId: 'cinco-tigres-felizes',
    storageBucket: 'cinco-tigres-felizes.firebasestorage.app',
    iosBundleId: 'com.example.cincoTigresFelizes',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU5tJPMl6meJ9afw6x76pgGyH9vCK9Rgo',
    appId: '1:75929189588:ios:f36017b70238adab87cf41',
    messagingSenderId: '75929189588',
    projectId: 'cinco-tigres-felizes',
    storageBucket: 'cinco-tigres-felizes.firebasestorage.app',
    iosBundleId: 'com.example.cincoTigresFelizes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTrI7dr8Of3huZqE2D7lehir8tzbnVle4',
    appId: '1:75929189588:web:a64dea2d5f6e50f187cf41',
    messagingSenderId: '75929189588',
    projectId: 'cinco-tigres-felizes',
    authDomain: 'cinco-tigres-felizes.firebaseapp.com',
    storageBucket: 'cinco-tigres-felizes.firebasestorage.app',
    measurementId: 'G-42F222GGLP',
  );
}
